Repository shouze/lp-ecue41, pull requests merged in 2021-11, with the labels that each got.

#1 Correction
  index.html
Labels: enhancement

#2 chore(ld): add auto publish of slides
  .github/workflows/ld-gh-pages-publish.yaml
Labels: enhancement

#3 fix: useless sudo
  README.md
Labels: bug

#4 doc: check docker compose installation
  README.md
Labels: documentation

#5 fix: refine commands
  README.md
Labels: bug
